# Generated by Django 4.1.2 on 2022-10-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsedata',
            name='img_link',
            field=models.URLField(null=True, verbose_name='Изображение'),
        ),
    ]
