# Generated by Django 4.1.2 on 2022-10-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_app', '0002_alter_parsedata_img_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedata',
            name='site_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя сайта'),
        ),
    ]
